---
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install Certs
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - 'apt-transport-https'
    - 'ca-certificates'

- name: Import public key
  apt_key:
    url: 'https://www.mongodb.org/static/pgp/server-3.2.asc'
    state: present

- name: Add repository
  apt_repository:
    filename: '/etc/apt/sources.list.d/mongodb-org-3.2.list'
    repo: 'deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse'
    state: present
    update_cache: yes

- name: install mongodb
  apt:
    name: mongodb-org
    state: present
    allow_unauthenticated: yes
    update_cache: yes

- name: Configure service supervisor
  systemd:
    name: mongod
    enabled: yes
    daemon_reload: true
    state: started
