---
- name: Check && install python
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install Python 2.x
      raw: test -e /usr/bin/python || apt -y install python-minimal
      changed_when: False
