- name: Deploy App
  hosts: app
  become: true
  tasks:

    - name: Install equipments
      become: true
      apt:
        name: git-all
        state: present

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "/home/{{deploy_user}}/reddit"
        version: monolith
      notify: restart puma

    - name: bundle install
      become: no
      bundler:
        state: present
        chdir: "/home/{{ deploy_user}}/reddit"

  handlers:
    - name: enable puma
      systemd:
        name: puma
        enabled: yes

    - name: restart puma
      systemd:
        name: puma
        state: restarted
