---
- name: Configure host and install ruby
  hosts: default
  become: true

  tasks:
    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install Certs
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - 'apt-transport-https'
        - 'ca-certificates'

    - name: Install Ruby and build-essential
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - 'ruby-full'
        - 'ruby-bundler'
        - 'build-essential'
